"""Recreate schema for SQLite"""

revision = '5c13d483ea2e'
down_revision = '20260410_230600'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_verified'), 'users', ['is_verified'], unique=False)
    op.create_table('analyses',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('repository_url', sa.String(length=500), nullable=False),
    sa.Column('repository_name', sa.String(length=255), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='analysis_status'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_analyses_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses'))
    )
    op.create_index(op.f('ix_analyses_status'), 'analyses', ['status'], unique=False)
    op.create_index(op.f('ix_analyses_user_id'), 'analyses', ['user_id'], unique=False)
    op.create_table('code_metrics',
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('commit_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_block_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_line_count', sa.Integer(), nullable=False),
    sa.Column('average_cyclomatic_complexity', sa.Float(), nullable=False),
    sa.Column('max_cyclomatic_complexity', sa.Integer(), nullable=False),
    sa.Column('maintainability_index', sa.Float(), nullable=False),
    sa.Column('technical_debt_score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_code_metrics_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code_metrics'))
    )
    op.create_index(op.f('ix_code_metrics_analysis_id'), 'code_metrics', ['analysis_id'], unique=True)
    op.create_table('reports',
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.Enum('csv', 'pdf', name='report_type'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_reports_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('s3_key', name=op.f('uq_reports_s3_key'))
    )
    op.create_index(op.f('ix_reports_analysis_id'), 'reports', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_analysis_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_code_metrics_analysis_id'), table_name='code_metrics')
    op.drop_table('code_metrics')
    op.drop_index(op.f('ix_analyses_user_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_status'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_users_is_verified'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
