"""add_tech_stack_to_code_metrics"""

revision = 'bb0762393dfe'
down_revision = '85fe329686c1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_metrics', sa.Column('tech_stack', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_metrics', 'tech_stack')
    # ### end Alembic commands ###
