"""Add organizations"""

revision = 'cf9a26588512'
down_revision = 'b2c3d4e5f6g7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('billing_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('organization_members',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('admin', 'developer', 'viewer', name='organization_role'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_members_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organization_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_members'))
    )
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.add_column('analyses', sa.Column('organization_id', sa.String(length=36), nullable=True))
    op.drop_constraint('uq_analyses_share_token', 'analyses', type_='unique')
    op.create_index(op.f('ix_analyses_organization_id'), 'analyses', ['organization_id'], unique=False)
    op.create_foreign_key(op.f('fk_analyses_organization_id_organizations'), 'analyses', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_vulnerabilities_id', table_name='vulnerabilities')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_vulnerabilities_id', 'vulnerabilities', ['id'], unique=False)
    op.drop_constraint(op.f('fk_analyses_organization_id_organizations'), 'analyses', type_='foreignkey')
    op.drop_index(op.f('ix_analyses_organization_id'), table_name='analyses')
    op.create_unique_constraint('uq_analyses_share_token', 'analyses', ['share_token'])
    op.drop_column('analyses', 'organization_id')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_table('organizations')
    # ### end Alembic commands ###
